var personas = [];

personas.push({Nombre: 'ANTONIO', Apellido: 'GARCIA', Sexo: 'M'});
personas.push({Nombre: 'JOSE', Apellido: 'GONZALEZ', Sexo: 'M'});
personas.push({Nombre: 'MANUEL', Apellido: 'RODRIGUEZ', Sexo: 'M'});
personas.push({Nombre: 'FRANCISCO', Apellido: 'FERNANDEZ', Sexo: 'M'});
personas.push({Nombre: 'JUAN', Apellido: 'LOPEZ', Sexo: 'M'});
personas.push({Nombre: 'DAVID', Apellido: 'MARTINEZ', Sexo: 'M'});
personas.push({Nombre: 'JOSE ANTONIO', Apellido: 'SANCHEZ', Sexo: 'M'});
personas.push({Nombre: 'JOSE LUIS', Apellido: 'PEREZ', Sexo: 'M'});
personas.push({Nombre: 'JAVIER', Apellido: 'GOMEZ', Sexo: 'M'});
personas.push({Nombre: 'JESUS', Apellido: 'MARTIN', Sexo: 'M'});
personas.push({Nombre: 'FRANCISCO JAVIER', Apellido: 'JIMENEZ', Sexo: 'M'});
personas.push({Nombre: 'CARLOS', Apellido: 'RUIZ', Sexo: 'M'});
personas.push({Nombre: 'DANIEL', Apellido: 'HERNANDEZ', Sexo: 'M'});
personas.push({Nombre: 'MIGUEL', Apellido: 'DIAZ', Sexo: 'M'});
personas.push({Nombre: 'RAFAEL', Apellido: 'MORENO', Sexo: 'M'});
personas.push({Nombre: 'MARIA CARMEN', Apellido: 'GARCIA', Sexo: 'F'});
personas.push({Nombre: 'MARIA', Apellido: 'GONZALEZ', Sexo: 'F'});
personas.push({Nombre: 'CARMEN', Apellido: 'RODRIGUEZ', Sexo: 'F'});
personas.push({Nombre: 'JOSEFA', Apellido: 'FERNANDEZ', Sexo: 'F'});
personas.push({Nombre: 'ISABEL', Apellido: 'LOPEZ', Sexo: 'F'});
personas.push({Nombre: 'ANA MARIA', Apellido: 'MARTINEZ', Sexo: 'F'});
personas.push({Nombre: 'MARIA DOLORES', Apellido: 'SANCHEZ', Sexo: 'F'});
personas.push({Nombre: 'MARIA PILAR', Apellido: 'PEREZ', Sexo: 'F'});
personas.push({Nombre: 'MARIA TERESA', Apellido: 'GOMEZ', Sexo: 'F'});
personas.push({Nombre: 'ANA', Apellido: 'MARTIN', Sexo: 'F'});
personas.push({Nombre: 'LAURA', Apellido: 'JIMENEZ', Sexo: 'F'});
personas.push({Nombre: 'FRANCISCA', Apellido: 'RUIZ', Sexo: 'F'});
personas.push({Nombre: 'ANTONIA', Apellido: 'HERNANDEZ', Sexo: 'F'});
personas.push({Nombre: 'DOLORES', Apellido: 'DIAZ', Sexo: 'F'});
personas.push({Nombre: 'MARIA ANGELES', Apellido: 'MORENO', Sexo: 'F'});